Unittests + has_pending_commit/confirm_commit
napalm-automation-community/napalm-arubaos-switch pull request #12
Opened 2021-11-17 14:38 UTC by hupebln

# One-line summary

Unittests + 2 new methods

## Description
- in order to test the package, Unittests have been implemented.
- has_pending_commit has been implemented to check if a commit is pending
- confirm_commit has been implemented to confirm a pending commit

## Types of Changes
- New feature (non-breaking change which adds functionality)
- Refactor/improvements
- Documentation / non-code

## Tasks
  - [ ] Test on device in our LAB

## Review
- [ ] Test on device in our LAB
- [ ] Documentation

2021-11-19 14:02 UTC, gcotone requested changes
Some suggestions added. The only breaking change compared to `0.1.1-1` is the `compare_config` functionality that could be addressed either here, or in a separate PR.

2021-11-19 14:02 UTC, gcotone commented on setup.py
> +    version="0.2.0",
Should we change this to `0.1.2` ?

2021-11-19 14:02 UTC, gcotone commented on napalm_arubaoss/helper/compare_config.py
> +def compare_config(self):
With the change to `requests_futures` library (instead of `requests`) and the use of `FuturesSession()`, the function `compare_config()` almost always return `''`, even when the candidate config is different from the running one. This is not the case with napalm-arubaos-switch `0.1.1-1`

2021-11-19 14:02 UTC, gcotone commented on napalm_arubaoss/helper/compare_config.py
> +def compare_config(self):
Looks like this bug was introduced in PR #8  and it's somehow related to an issue in ArubaOS REST API when the client reuses the TCP connection for multiple requests.

It was mentioned in the code here: https://github.com/napalm-automation-community/napalm-arubaos-switch/blob/01aee99169c477ab75f26fd35fbee13851291d92/napalm_arubaoss/ArubaOS.py#L84-L86
Also reported on Aruba support portal: https://community.arubanetworks.com/community-home/digestviewer/viewthread?MID=28798#bme4aa3703-e476-4880-9cb4-9b208f86b2f4

2021-11-19 14:02 UTC, gcotone commented on napalm_arubaoss/helper/commit_config.py
> +        load_replace_candidate(self=self, config=candidate_confirm)
I think `load_replace_candidate` is not needed here, the behavior should be the same as with a normal commit.

2021-11-22 12:29 UTC, hupebln commented on napalm_arubaoss/helper/compare_config.py
> +def compare_config(self):
As discussed internally we will merge it with these changes and implement the keep_alive either again by using requests or by using a different library.

2021-11-22 13:59 UTC, gcotone approved these changes

2021-11-22 14:00 UTC, merged