Connection rebuild
napalm-automation-community/napalm-arubaos-switch pull request #14
Opened 2021-12-10 09:44 UTC by hupebln

# One-line summary

> Issue : #13 

## Description
- Python requests has been re-implemented again to avoid sharing the TCP Session as it can cause issues with ArubaOS devices
- compare_config needed a sleep between 2 calls as the device seems to take a little time to process a diff request

## Types of Changes
- Bug fix (non-breaking change which fixes an issue)

2021-12-14 14:07 UTC, gcotone requested changes

2021-12-14 14:07 UTC, gcotone commented on napalm_arubaoss/helper/base.py
> +        self._apisession.keep_alive = optional_args.get(
Seems like keep_alive argument does nothing atm, and `'Connection': 'keep-alive'` is always set unless overidden: https://github.com/psf/requests/blob/2d2447e210cf0b9e8c7484bfc6f158de9b24c171/requests/utils.py#L881

2021-12-14 14:07 UTC, gcotone commented on napalm_arubaoss/helper/base.py
> +        self._apisession.keep_alive = optional_args.get(
To disable keep-alive, setting `'Connection': 'close'` in the request headers is now the way to go as shown here: https://github.com/psf/requests/pull/5649/files ((and commented #L69)

After running some [tests](https://gist.github.com/gcotone/d54dc6b9476cab74f1fa891acd29601c) on most methods supported by this driver, disabling keep-alive showed a twofold speed improvement (script runtime 51.649 vs 2:05.46).

I'd suggest setting/uncommenting line 69 if `optional_args.get("keepalive") = True`

2021-12-14 14:07 UTC, gcotone commented on napalm_arubaoss/helper/compare_config.py
> +            return diff_output.json()
LGTM

2021-12-14 15:01 UTC, hupebln commented on napalm_arubaoss/helper/base.py
> +        self._apisession.keep_alive = optional_args.get(
Would it mean that [this statement](https://github.com/napalm-automation-community/napalm-arubaos-switch/blob/master/napalm_arubaoss/ArubaOS.py#L84-L86) is not valid anymore and you would suggest to use the same connection?
Did you mean setting `"Connection": "close"` when keepalive/keep_alive is set to False? And what would be the default? keepalive = False or True?

2021-12-14 15:06 UTC, hupebln commented on napalm_arubaoss/helper/base.py
> +        self._apisession.keep_alive = optional_args.get(
So would `"Connection": "close"` be the default and we don't set it if **keepalive** is set to **True**? Or the other way around?

2021-12-14 15:09 UTC, gcotone commented on napalm_arubaoss/helper/base.py
> +        self._apisession.keep_alive = optional_args.get(
> `"Connection": "close"` should be the default and we don't set it if keepalive is set to True.

Yes.  Sorry for the confusion.

2021-12-15 10:30 UTC, gcotone approved these changes

2021-12-15 14:13 UTC, merged